Repository ScorexFoundation/sigmastate-interpreter, pull requests merged in 2019-06, with the labels that each got.

#508 SMethod tests
  src/main/scala/org/ergoplatform/ErgoBox.scala
  src/main/scala/org/ergoplatform/ErgoConstants.scala
  src/main/scala/org/ergoplatform/ErgoLikeContext.scala
  src/main/scala/sigmastate/interpreter/Interpreter.scala
  src/main/scala/sigmastate/serialization/SigmaSerializer.scala
  src/main/scala/sigmastate/trees.scala
  src/main/scala/sigmastate/types.scala
  src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
  src/test/scala/sigmastate/lang/SigmaTyperTest.scala
  src/test/scala/special/sigma/SigmaDslTest.scala
Labels: ready for merge

#515 update scorex-util 0.1.3 -> 0.1.4 (fixed getShort)
  build.sbt
  src/test/scala/sigmastate/serialization/ConcreteCollectionSerializerSpecification.scala
Labels: ready for merge

#521 Fix `MethodNotFound` exception in ByteBuffer on Java 8
  build.sbt
Labels: wip

#524 Remove/soften "whenever" requirements to reduce the number of discarded evaluations
  build.sbt
  src/test/scala/sigmastate/TestingInterpreterSpecification.scala
  src/test/scala/special/sigma/SigmaDslTest.scala
Labels: ready for merge

#528 Check proposition size limit on deserialization
  src/main/scala/org/ergoplatform/ErgoConstants.scala
  src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
  src/main/scala/sigmastate/serialization/SigmaSerializer.scala
  src/main/scala/sigmastate/serialization/ValueSerializer.scala
  src/main/scala/sigmastate/utils/SigmaByteReader.scala
  src/test/scala/sigmastate/eval/SizedTests.scala
  src/test/scala/sigmastate/serialization/DeserializationResilience.scala
Labels: wip

#527 More diversity of scripts in generators
  src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala
  src/test/scala/org/ergoplatform/ErgoLikeTransactionSpec.scala
  src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
  src/test/scala/sigmastate/lang/SigmaSpecializerTest.scala
  src/test/scala/sigmastate/lang/SigmaTyperTest.scala
  src/test/scala/sigmastate/serialization/SerializationSpecification.scala
  src/test/scala/sigmastate/serialization/SigSerializerSpecification.scala
  src/test/scala/sigmastate/serialization/generators/ConcreteCollectionGenerators.scala
  src/test/scala/sigmastate/serialization/generators/ObjectGenerators.scala
  src/test/scala/sigmastate/serialization/generators/RelationGenerators.scala
  src/test/scala/sigmastate/serialization/generators/TransformerGenerators.scala
  src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala
  src/test/scala/sigmastate/utils/HelpersTests.scala
  src/test/scala/sigmastate/utils/SparseArrayContainerSpecification.scala
  src/test/scala/sigmastate/utxo/SerializationRoundTripSpec.scala
  src/test/scala/special/sigma/SigmaTypeGens.scala
Labels: wip

#529 Check MaxPropositionSize in reader
  src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
  src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
  src/main/scala/sigmastate/serialization/SigmaSerializer.scala
  src/main/scala/sigmastate/serialization/ValueSerializer.scala
  src/main/scala/sigmastate/utils/SigmaByteReader.scala
  src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
  src/test/scala/sigmastate/serialization/DeserializationResilience.scala
  src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
  src/test/scala/sigmastate/serialization/SerializationSpecification.scala
Labels: ready for merge, wip

#503 Soft-Forkability: table of allowed opcodes in cost function
  src/main/scala/org/ergoplatform/validation/ValidationRules.scala
  src/main/scala/sigmastate/eval/Evaluation.scala
  src/main/scala/sigmastate/eval/TreeBuilding.scala
  src/main/scala/sigmastate/lang/SigmaBuilder.scala
  src/main/scala/sigmastate/serialization/OpCodes.scala
  src/main/scala/sigmastate/serialization/SigmaSerializer.scala
  src/main/scala/sigmastate/serialization/ValueSerializer.scala
  src/main/scala/sigmastate/trees.scala
  src/test/scala/sigmastate/SoftForkabilitySpecification.scala
  src/test/scala/sigmastate/eval/CompilerItTest.scala
Labels: ready for merge

#523 Simplify cost graphs and speedup costing performance
  build.sbt
  docs/releasenotes.md
  sigma-api/src/main/scala/special/sigma/package.scala
  sigma-library/src/main/scala/special/sigma/impl/SigmaDslImpl.scala
  src/main/scala/org/ergoplatform/ErgoBoxCandidate.scala
  src/main/scala/org/ergoplatform/ErgoConstants.scala
  src/main/scala/org/ergoplatform/validation/ValidationRules.scala
  src/main/scala/sigmastate/eval/CostingRules.scala
  src/main/scala/sigmastate/eval/IRContext.scala
  src/main/scala/sigmastate/eval/RuntimeCosting.scala
  src/main/scala/sigmastate/eval/Sized.scala
  src/main/scala/sigmastate/interpreter/Interpreter.scala
  src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
  src/main/scala/sigmastate/serialization/SigmaSerializer.scala
  src/main/scala/sigmastate/serialization/ValueSerializer.scala
  src/main/scala/sigmastate/types.scala
  src/main/scala/sigmastate/utils/SigmaByteReader.scala
  src/test/scala/org/ergoplatform/ErgoScriptPredefSpec.scala
  src/test/scala/sigmastate/CostingSpecification.scala
  src/test/scala/sigmastate/SoftForkabilitySpecification.scala
  src/test/scala/sigmastate/eval/SizedTests.scala
  src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
  src/test/scala/sigmastate/serialization/DeserializationResilience.scala
  src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
  src/test/scala/sigmastate/serialization/SerializationSpecification.scala
  src/test/scala/sigmastate/serialization/generators/RelationGenerators.scala
  src/test/scala/sigmastate/serialization/generators/ValueGenerators.scala
  src/test/scala/sigmastate/utils/GenInfoObjects.scala
  src/test/scala/sigmastate/utils/GenPredefFuncsApp.scala
  src/test/scala/sigmastate/utils/GenSerializers.scala
  src/test/scala/sigmastate/utils/SpecGen.scala
  src/test/scala/sigmastate/utxo/SpamSpecification.scala
  src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
Labels: ready for merge

#530 Cost Limit moved to Context
  src/main/scala/org/ergoplatform/ErgoConstants.scala
  src/main/scala/org/ergoplatform/ErgoLikeContext.scala
  src/main/scala/org/ergoplatform/ErgoLikeInterpreter.scala
  src/main/scala/sigmastate/interpreter/Interpreter.scala
  src/main/scala/sigmastate/interpreter/InterpreterContext.scala
  src/main/scala/sigmastate/utxo/CostTable.scala
  src/test/scala/org/ergoplatform/ErgoScriptPredefSpec.scala
  src/test/scala/org/ergoplatform/dsl/TestContractSpec.scala
  src/test/scala/sigmastate/CostingSpecification.scala
  src/test/scala/sigmastate/helpers/ContextEnrichingTestProvingInterpreter.scala
  src/test/scala/sigmastate/helpers/ErgoLikeTestProvingInterpreter.scala
  src/test/scala/sigmastate/helpers/ErgoTransactionValidator.scala
  src/test/scala/sigmastate/serialization/generators/ObjectGenerators.scala
  src/test/scala/sigmastate/utxo/SpamSpecification.scala
  src/test/scala/sigmastate/utxo/examples/Rule110Specification.scala
  src/test/scala/special/sigma/SigmaTestingData.scala
Labels: ready for merge

#535 Remove dangerous rule + more descriptions
  src/main/scala/org/ergoplatform/validation/ValidationRules.scala
  src/main/scala/sigmastate/eval/RuntimeCosting.scala
  src/main/scala/sigmastate/interpreter/Interpreter.scala
  src/main/scala/sigmastate/serialization/DataSerializer.scala
  src/main/scala/sigmastate/serialization/ErgoTreeSerializer.scala
  src/main/scala/sigmastate/serialization/TypeSerializer.scala
  src/main/scala/sigmastate/types.scala
  src/main/scala/sigmastate/utils/SigmaByteReader.scala
  src/test/scala/sigmastate/SoftForkabilitySpecification.scala
  src/test/scala/sigmastate/serialization/DeserializationResilience.scala
  src/test/scala/sigmastate/serialization/ErgoTreeSerializerSpecification.scala
Labels: ready for merge

#540 Fail spam specification
  src/test/scala/sigmastate/utxo/SpamSpecification.scala
Labels: ready for merge

#541 add Coveralls
  .travis.yml
  project/plugins.sbt
  src/test/scala/sigmastate/utxo/SpamSpecification.scala
Labels: ready for merge

#544 restore SpamSpec timeout
  .travis.yml
  src/test/scala/sigmastate/utxo/SpamSpecification.scala
Labels: ready for merge

#542 add more SigmaDslTest equivalence tests
  sigma-api/src/main/scala/special/sigma/SigmaDsl.scala
  src/main/scala/sigmastate/eval/Evaluation.scala
  src/main/scala/sigmastate/eval/RuntimeCosting.scala
  src/test/scala/special/sigma/SigmaDslTest.scala
Labels: ready for merge

#516 Add more tests to CostingSpecification
  src/main/scala/sigmastate/eval/CostingDataContext.scala
  src/main/scala/sigmastate/eval/CostingRules.scala
  src/main/scala/sigmastate/utxo/CostTable.scala
  src/test/scala/sigmastate/CostingSpecification.scala
Labels: ready for merge

#549 Account for ErgoTree.complexity in the prover
  src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
  src/test/scala/sigmastate/CostingSpecification.scala
  src/test/scala/sigmastate/utxo/SpamSpecification.scala
  src/test/scala/sigmastate/utxo/examples/IcoExample.scala
Labels: ready for merge

#548 Fix exp costing
  src/main/scala/sigmastate/eval/TreeBuilding.scala
  src/test/scala/sigmastate/CostingSpecification.scala
  src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
  src/test/scala/sigmastate/utxo/SpamSpecification.scala
  src/test/scala/special/sigma/SigmaDslTest.scala
Labels: ready for merge
