Repository ScorexFoundation/sigmastate-interpreter, pull requests merged in 2020-09, with the labels that each got.

#682 Improving hints generation to avoid using the same commitment twice
  sigmastate/src/main/scala/sigmastate/SigSerializer.scala
  sigmastate/src/main/scala/sigmastate/UnprovenTree.scala
  sigmastate/src/main/scala/sigmastate/Values.scala
  sigmastate/src/main/scala/sigmastate/interpreter/Hint.scala
  sigmastate/src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
  sigmastate/src/main/scala/sigmastate/interpreter/ProverUtils.scala
  sigmastate/src/main/scala/sigmastate/trees.scala
  sigmastate/src/test/scala/sigmastate/helpers/ErgoLikeTestProvingInterpreter.scala
  sigmastate/src/test/scala/sigmastate/utxo/DistributedSigSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/ProverSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/CoopExampleSpecification.scala
Labels: S-ready-for-merge

#680 Test vectors for cost estimation
  sigmastate/src/main/scala/org/ergoplatform/ErgoBox.scala
  sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
  sigmastate/src/main/scala/sigmastate/eval/IRContext.scala
  sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
  sigmastate/src/test/scala/org/ergoplatform/ErgoAddressSpecification.scala
  sigmastate/src/test/scala/org/ergoplatform/ErgoScriptPredefSpec.scala
  sigmastate/src/test/scala/org/ergoplatform/dsl/TestContractSpec.scala
  sigmastate/src/test/scala/sigmastate/CostingSpecification.scala
  sigmastate/src/test/scala/sigmastate/FailingToProveSpec.scala
  sigmastate/src/test/scala/sigmastate/SoftForkabilitySpecification.scala
  sigmastate/src/test/scala/sigmastate/TestingInterpreterSpecification.scala
  sigmastate/src/test/scala/sigmastate/TypesSpecification.scala
  sigmastate/src/test/scala/sigmastate/eval/ErgoScriptTestkit.scala
  sigmastate/src/test/scala/sigmastate/eval/EvaluationTest.scala
  sigmastate/src/test/scala/sigmastate/helpers/ErgoLikeContextTesting.scala
  sigmastate/src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
  sigmastate/src/test/scala/sigmastate/helpers/TestingHelpers.scala
  sigmastate/src/test/scala/sigmastate/serialization/SigSerializerSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/AVLTreeScriptsSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/BlockchainSimulationSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/CollectionOperationsSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/ErgoLikeInterpreterSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/benchmarks/CrowdfundingBenchmark.scala
  sigmastate/src/test/scala/sigmastate/utxo/blockchain/BlockchainSimulationTestingCommons.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/CoinEmissionSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/ColdWalletAdvContractExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/ColdWalletContractExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/CoopExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/DHTupleExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/DemurrageExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/FsmExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/IcoExample.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/LetsSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/MASTExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/MixExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/OracleExamplesSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/RPSGameExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/ReversibleTxExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/Rule110Specification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/TimedPaymentExampleSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/TrustlessLETS.scala
  sigmastate/src/test/scala/sigmastate/utxo/examples/XorGameExampleSpecification.scala
  sigmastate/src/test/scala/special/sigma/ContractsTestkit.scala
  sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
  sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
  sigmastate/src/test/scala/special/sigma/SigmaTestingData.scala
Labels: S-ready-for-merge, S-ready-for-review

#690 Optimize memory footprint
  common/src/main/scala/scalan/TypeDesc.scala
  core/src/main/scala/scalan/Entities.scala
  library-impl/src/main/scala/special/collection/CollsOverArrays.scala
  sigma-api/src/main/scala/special/sigma/SigmaDsl.scala
  sigmastate/src/main/scala/org/ergoplatform/ErgoLikeContext.scala
  sigmastate/src/main/scala/sigmastate/Values.scala
  sigmastate/src/main/scala/sigmastate/eval/CostingDataContext.scala
  sigmastate/src/main/scala/sigmastate/eval/Evaluation.scala
  sigmastate/src/main/scala/sigmastate/eval/RuntimeCosting.scala
  sigmastate/src/main/scala/sigmastate/eval/TreeBuilding.scala
  sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
  sigmastate/src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
  sigmastate/src/main/scala/sigmastate/interpreter/ProverResult.scala
  sigmastate/src/main/scala/sigmastate/lang/SigmaBinder.scala
  sigmastate/src/main/scala/sigmastate/lang/SigmaParser.scala
  sigmastate/src/main/scala/sigmastate/lang/SigmaPredef.scala
  sigmastate/src/main/scala/sigmastate/lang/SigmaSpecializer.scala
  sigmastate/src/main/scala/sigmastate/lang/SigmaTyper.scala
  sigmastate/src/main/scala/sigmastate/lang/SourceContext.scala
  sigmastate/src/main/scala/sigmastate/lang/Terms.scala
  sigmastate/src/main/scala/sigmastate/lang/Types.scala
  sigmastate/src/main/scala/sigmastate/serialization/TypeSerializer.scala
  sigmastate/src/main/scala/sigmastate/trees.scala
  sigmastate/src/main/scala/sigmastate/types.scala
  sigmastate/src/main/scala/sigmastate/utils/SigmaByteReader.scala
  sigmastate/src/main/scala/sigmastate/utxo/transformers.scala
  sigmastate/src/test/scala/sigmastate/ErgoTreeSpecification.scala
  sigmastate/src/test/scala/sigmastate/TypesSpecification.scala
  sigmastate/src/test/scala/sigmastate/helpers/NegativeTesting.scala
  sigmastate/src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
  sigmastate/src/test/scala/sigmastate/lang/LangTests.scala
  sigmastate/src/test/scala/sigmastate/lang/SigmaCompilerTest.scala
  sigmastate/src/test/scala/sigmastate/lang/SigmaTyperTest.scala
  sigmastate/src/test/scala/sigmastate/utils/SpecGen.scala
  sigmastate/src/test/scala/sigmastate/utxo/BasicOpsSpecification.scala
Labels: S-ready-for-review
