Repository ScorexFoundation/sigmastate-interpreter, pull requests merged in 2021-01, with the labels that each got.

#707 Test vectors for comparison operations
  common/src/main/scala/scalan/MutableLazy.scala
  common/src/main/scala/scalan/TypeDesc.scala
  common/src/main/scala/scalan/util/CollectionUtil.scala
  common/src/main/scala/scalan/util/Extensions.scala
  common/src/main/scala/scalan/util/ReflectionUtil.scala
  common/src/test/scala/scalan/BaseTests.scala
  core/src/main/scala/scalan/Base.scala
  core/src/main/scala/scalan/TypeDescs.scala
  core/src/main/scala/scalan/primitives/OrderingOps.scala
  core/src/main/scala/scalan/primitives/Thunks.scala
  core/src/main/scala/scalan/primitives/Tuples.scala
  core/src/main/scala/scalan/staged/Transforming.scala
  library-api/src/main/scala/special/collection/package.scala
  library/src/main/scala/scalan/Library.scala
  library/src/main/scala/special/collection/impl/CollsImpl.scala
  library/src/main/scala/special/collection/impl/ConcreteCostsImpl.scala
  library/src/main/scala/special/collection/impl/ConcreteSizesImpl.scala
  library/src/main/scala/special/collection/impl/CostedOptionsImpl.scala
  library/src/main/scala/special/collection/impl/CostsImpl.scala
  library/src/main/scala/special/collection/impl/MonoidInstancesImpl.scala
  library/src/main/scala/special/collection/impl/MonoidsImpl.scala
  library/src/main/scala/special/collection/impl/SizesImpl.scala
  library/src/main/scala/special/wrappers/impl/WrappersSpecImpl.scala
  library/src/main/scala/wrappers/scala/impl/WOptionsImpl.scala
  library/src/main/scala/wrappers/scalan/impl/WRTypesImpl.scala
  library/src/main/scala/wrappers/special/impl/WSpecialPredefsImpl.scala
  library/src/test/scala/special/collections/CollGens.scala
  library/src/test/scala/special/collections/CollsTests.scala
  sigma-library/src/main/scala/special/sigma/impl/CostedObjectsImpl.scala
  sigma-library/src/main/scala/special/sigma/impl/SigmaDslImpl.scala
  sigmastate/src/main/scala/sigmastate/eval/TreeBuilding.scala
  sigmastate/src/main/scala/sigmastate/types.scala
  sigmastate/src/test/scala/sigmastate/ErgoTreeSpecification.scala
  sigmastate/src/test/scala/sigmastate/helpers/SigmaTestingCommons.scala
  sigmastate/src/test/scala/sigmastate/helpers/TestingHelpers.scala
  sigmastate/src/test/scala/special/sigma/SigmaDslSpecification.scala
  sigmastate/src/test/scala/special/sigma/SigmaDslTesting.scala
  sigmastate/src/test/scala/special/sigma/SigmaTestingData.scala
  sigmastate/src/test/scala/special/sigma/SigmaTypeGens.scala
Labels: S-ready-for-review

#713 Add missing ScalaDocs
  sigmastate/src/main/scala/sigmastate/lang/Terms.scala
  sigmastate/src/main/scala/sigmastate/trees.scala
  sigmastate/src/main/scala/sigmastate/types.scala
Labels: A-docs, P2-medium, S-wip

#685 signMessage / verifyMessage for signing and verifying arbitrary messages
  sigmastate/src/main/scala/sigmastate/SigSerializer.scala
  sigmastate/src/main/scala/sigmastate/interpreter/Interpreter.scala
  sigmastate/src/main/scala/sigmastate/interpreter/ProverInterpreter.scala
  sigmastate/src/main/scala/sigmastate/interpreter/ProverUtils.scala
  sigmastate/src/test/scala/sigmastate/crypto/SigningSpecification.scala
  sigmastate/src/test/scala/sigmastate/utxo/DistributedSigSpecification.scala
Labels: S-ready-for-merge
